<?php
/*
 * Copyright (C) 2015
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 as published
 * by the Free Software Foundation.
 *
 * If the program is linked with libraries which are licensed under one of
 * the following licenses, the combination of the program with the linked
 * library is not considered a "derivative work" of the program:
 *
 *     - Apache License, version 2.0
 *     - Apache Software License, version 1.0
 *     - GNU Lesser General Public License, version 3
 *     - Mozilla Public License, versions 1.0, 1.1 and 2.0
 *     - Common Development and Distribution License (CDDL), version 1.0
 *
 * Therefore the distribution of the program linked with libraries licensed
 * under the aforementioned licenses, is permitted by the copyright holders
 * if the distribution is compliant with both the GNU General Public
 * License version 2 and the aforementioned licenses.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
 * Public License for more details.
 */
 
include_once 'inc/dataset.inc';
include_once 'inc/webservice.inc';

//
// Form creation
//
function n52_waterinneu_form($form, &$form_state) {
	
	$form ['type'] = array (
			'#type' => 'radios',
			'#title' => t( 'Type of Content' ),
			'#options' => array (
					'dataset' => t('Dataset'),
					'webservice' => t('Webservice'),
					'package' => t('Software Package'),
					'project' => t('Project'),
			),
			'#description' => t ( 'Select the type of content you would like to add.' ),
			'#required' => TRUE,
	);
	$form = dataset_form($form);
	$form = webservice_form($form);
	
	//
	// ADDITIONAL INFORMATION form
	//
	$form['more_info'] = array (
			'#type' => 'fieldset',
			'#title' => t('Additional Information'),
			'#collapsible' => TRUE,
			'#collapsed' => TRUE,
			'#states' => array (
					'expanded' => array (
						':input[name="type"]' => array ('checked' => TRUE),
					),
			),
					
	);
	
	$form['more_info']['license'] = array (
			'#type' => 'select',
			'#title' => t('License'),
			// read options from file or system method
			'#options' => array (
					'free' => t('For Free'),
					'public_domain' => t('Public domain'),
					'fees' => t('Payment required')
			),
			'#default_value' => 'free',
			'#description' => t('Select the license to access the content.'),
	);
	
	$form ['submit_button'] = array (
			'#type' => 'submit',
			'#value' => t('Add to system'), 
	);
	
	return $form;
}

/** 
 * Implements hook_form_validate()
 *
 * Form validation
 */
function n52_waterinneu_form_validate($form, &$form_state) {
	$type = $form_state ['values'] ['type'];
	if ($type === 'dataset') {
		$mail = $form_state['values']['author_email'];
		if (!valid_email_address($mail)) {
			// http://www.rfc-editor.org/errata_search.php?rfc=3696
			form_set_error('author_email',
					t(
							'Please enter a valid email address. 
							The according <a href="@mail-spec">Specification</a>
							and <a href="@mail-spec-updates">some updates</a> are available online.',
							array (
									'@mail-spec' => 'https://tools.ietf.org/html/rfc3696',
									'@mail-spec-updates' => 'http://www.rfc-editor.org/errata_search.php?rfc=3696',
							)
					)
			);
		}
	}
	if ($type === 'dataset' || $type === 'webservice') {
		$url = $form_state['values']['url'];
		if (!valid_url($url,TRUE)) {
			form_set_error('$url',
					t(
							'Please enter a valid URL.
							The according <a href="@url-spec">Specification</a>
							and <a href="@url-spec-updates">some updates</a> are available online.',
							array (
									'@url-spec'=> 'https://tools.ietf.org/html/rfc1738',
									'@url-spec-updates' => 'https://www.rfc-editor.org/errata_search.php?rfc=1738',
							)
					)		
			);
		}
	}
}

/**
 * Implements hook_form_submit(..)
 */
function n52_waterinneu_form_submit($form, &$form_state) {
	// submission function called by drupal
	drupal_set_message("Form is submitted to nowhere, thanks for your time! Just for demo purposes.");
}

/**
 * Implements hook_menu()
 * 
 * Form WebUI
 */
function n52_waterinneu_menu() {
	$items = array ();
	
	// this creates a URL that will call this form at "examples/form-example"
	$items ['n52-waterinneu/add'] = array (
			// page title
			'title' => 'Add new dataset',
			'description' => 'A form to add a new dataset.',
			// this is the function that will be called when the page is accessed. for a form, use drupal_get_form
			'page callback' => 'drupal_get_form',
			'page arguments' => array ('n52_waterinneu_form'),
			'access arguments' => array ('waterinneu add content')
	);
	return $items;
}

/**
 * Implements hook_permission().
 *
 * Defines a new permission called 'waterinneu add content'.
 */
function n52_waterinneu_permission() {
	$permissions = array ();
	
	$permissions ['waterinneu add content'] = array(
					'title' => t('WaterInnEU Add Content'),
					'description' => t('Allows users to add WaterInnEU content.')
	);
	
	return $permissions;
}

/**
 * Implements hook_form_alter()
 * 
 */
function n52_waterinneu_form_n52_waterinneu_form_alter(&$form, &$form_state, $form_id) {
	// if ($form_id === 'n52_waterinneu_form') {
	// drupal_set_message( $form_id );
	// }
}
