<?php
/**
 * @file
 * menu_link.058258c2989cd9b5245350f4262bd62303e30d2d.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/regional/i18n',
  'link_title' => 'Multilingual settings',
  'menu_name' => 'management',
  'weight' => '10',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Configure extended options for multilingual content and translations.',
    ),
  ),
  'router_path' => 'admin/config/regional/i18n',
  'parent_identifier' => '29a0beace8faac4356003f60d9b4c5feb87d38f3',
);

$dependencies = array(
  'menu_link.29a0beace8faac4356003f60d9b4c5feb87d38f3' => 'menu_link.29a0beace8faac4356003f60d9b4c5feb87d38f3',
);

$optional = array();

$modules = array();
