<?php
/**
 * @file
 * menu_link.a0ac7769dd155924a164eb528a16bc61c42033cf.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/media',
  'link_title' => 'Media',
  'menu_name' => 'management',
  'weight' => '-10',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Media tools.',
    ),
  ),
  'router_path' => 'admin/config/media',
  'parent_identifier' => '981d1362cf2de95e180c0b90045770044c40adc6',
);

$dependencies = array(
  'menu_link.981d1362cf2de95e180c0b90045770044c40adc6' => 'menu_link.981d1362cf2de95e180c0b90045770044c40adc6',
);

$optional = array();

$modules = array();
