<?php
/**
 * @file
 * menu_link.bfcb7d3228e8c15cf5f1b6b40230432a5e8736ce.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'user/logout',
  'link_title' => 'Log out',
  'menu_name' => 'user-menu',
  'weight' => '10',
  'expanded' => '0',
  'options' => array(),
  'router_path' => 'user/logout',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.user_menu' => 'menu.user_menu',
);

$optional = array();

$modules = array();
