<?php
/**
 * @file
 * menu_link.1adbc0f3822aea55a615b906a17ceed183a56094.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/media/file-system',
  'link_title' => 'File system',
  'menu_name' => 'management',
  'weight' => '-10',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Tell Drupal where to store uploaded files and how they are accessed.',
    ),
  ),
  'router_path' => 'admin/config/media/file-system',
  'parent_identifier' => 'a0ac7769dd155924a164eb528a16bc61c42033cf',
);

$dependencies = array(
  'menu_link.a0ac7769dd155924a164eb528a16bc61c42033cf' => 'menu_link.a0ac7769dd155924a164eb528a16bc61c42033cf',
);

$optional = array();

$modules = array();
