<?php
/**
 * @file
 * menu_link.1cf7f51f65269905dde8a74fac5c14380fdeedd7.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/workflow',
  'link_title' => 'Workflow',
  'menu_name' => 'management',
  'weight' => '5',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Content workflow, editorial workflow tools.',
    ),
  ),
  'router_path' => 'admin/config/workflow',
  'parent_identifier' => '981d1362cf2de95e180c0b90045770044c40adc6',
);

$dependencies = array(
  'menu_link.981d1362cf2de95e180c0b90045770044c40adc6' => 'menu_link.981d1362cf2de95e180c0b90045770044c40adc6',
);

$optional = array();

$modules = array();
