<?php
/**
 * @file
 * menu_link.7fa6a77950f9dfec910f197544505e3fb2f92723.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'node/add',
  'link_title' => 'Add content',
  'menu_name' => 'navigation',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(),
  'router_path' => 'node/add',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.navigation' => 'menu.navigation',
);

$optional = array();

$modules = array();
