<?php
/**
 * @file
 * menu_link.9866f27a9b57b4c9309f2a33b11f318c4b6c852e.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/structure',
  'link_title' => 'Structure',
  'menu_name' => 'management',
  'weight' => '-8',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Administer blocks, content types, menus, etc.',
    ),
  ),
  'router_path' => 'admin/structure',
  'parent_identifier' => '713f7554ad180f9b7c569b7e4c1cb974c931e048',
);

$dependencies = array(
  'menu_link.713f7554ad180f9b7c569b7e4c1cb974c931e048' => 'menu_link.713f7554ad180f9b7c569b7e4c1cb974c931e048',
);

$optional = array();

$modules = array();
