<?php
/**
 * @file
 * menu_link.d940cbf5f66b498ad23d197ebb956513dfda688b.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'user',
  'link_title' => 'User account',
  'menu_name' => 'user-menu',
  'weight' => '-10',
  'expanded' => '0',
  'options' => array(
    'alter' => TRUE,
  ),
  'router_path' => 'user',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.user_menu' => 'menu.user_menu',
);

$optional = array();

$modules = array();
