<?php
/**
 * @file
 * menu_link.981d1362cf2de95e180c0b90045770044c40adc6.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config',
  'link_title' => 'Configuration',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Administer settings.',
    ),
  ),
  'router_path' => 'admin/config',
  'parent_identifier' => '713f7554ad180f9b7c569b7e4c1cb974c931e048',
);

$dependencies = array(
  'menu_link.713f7554ad180f9b7c569b7e4c1cb974c931e048' => 'menu_link.713f7554ad180f9b7c569b7e4c1cb974c931e048',
);

$optional = array();

$modules = array();
