<?php
/**
 * @file
 * menu_link.ec7953be97a7eed43ff5b80b7d9f5782a1b7de8a.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/search/clean-urls',
  'link_title' => 'Clean URLs',
  'menu_name' => 'management',
  'weight' => '5',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Enable or disable clean URLs for your site.',
    ),
  ),
  'router_path' => 'admin/config/search/clean-urls',
  'parent_identifier' => 'ef0082661602f85e5c700d4bd929cfa3db5d543f',
);

$dependencies = array(
  'menu_link.ef0082661602f85e5c700d4bd929cfa3db5d543f' => 'menu_link.ef0082661602f85e5c700d4bd929cfa3db5d543f',
);

$optional = array();

$modules = array();
