<?php
/**
 * @file
 * menu_link.da5f9c423c621e751a68fa86e0d6269370c22a9e.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/regional/settings',
  'link_title' => 'Regional settings',
  'menu_name' => 'management',
  'weight' => '-20',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Settings for the site\'s default time zone and country.',
    ),
  ),
  'router_path' => 'admin/config/regional/settings',
  'parent_identifier' => '29a0beace8faac4356003f60d9b4c5feb87d38f3',
);

$dependencies = array(
  'menu_link.29a0beace8faac4356003f60d9b4c5feb87d38f3' => 'menu_link.29a0beace8faac4356003f60d9b4c5feb87d38f3',
);

$optional = array();

$modules = array();
