<?php
/**
 * @file
 * menu_link.e4bf90832226d3be755b8c7e87c6b242beaeedb8.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/services',
  'link_title' => 'Web services',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Tools related to web services.',
    ),
  ),
  'router_path' => 'admin/config/services',
  'parent_identifier' => '981d1362cf2de95e180c0b90045770044c40adc6',
);

$dependencies = array(
  'menu_link.981d1362cf2de95e180c0b90045770044c40adc6' => 'menu_link.981d1362cf2de95e180c0b90045770044c40adc6',
);

$optional = array();

$modules = array();
