<?php
/**
 * @file
 * menu_link.2ef364dcee3db910b2cb9c645aecc1c896d73bb0.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/system/site-information',
  'link_title' => 'Site information',
  'menu_name' => 'management',
  'weight' => '-20',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Change site name, e-mail address, slogan, default front page, and number of posts per page, error pages.',
    ),
  ),
  'router_path' => 'admin/config/system/site-information',
  'parent_identifier' => '4e354a16bb1634106a3ada7d78189d4d30588ae6',
);

$dependencies = array(
  'menu_link.4e354a16bb1634106a3ada7d78189d4d30588ae6' => 'menu_link.4e354a16bb1634106a3ada7d78189d4d30588ae6',
);

$optional = array();

$modules = array();
