<?php
/**
 * @file
 * menu_link.1e75a50a1abf9b74e81488bb43585e532eaf6587.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/modules',
  'link_title' => 'Modules',
  'menu_name' => 'management',
  'weight' => '-2',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Extend site functionality.',
    ),
  ),
  'router_path' => 'admin/modules',
  'parent_identifier' => '713f7554ad180f9b7c569b7e4c1cb974c931e048',
);

$dependencies = array(
  'menu_link.713f7554ad180f9b7c569b7e4c1cb974c931e048' => 'menu_link.713f7554ad180f9b7c569b7e4c1cb974c931e048',
);

$optional = array();

$modules = array();
