<?php
/**
 * @file
 * menu_link.6e9b944c771415a0ccba38da3b419ea22c255640.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/reports',
  'link_title' => 'Reports',
  'menu_name' => 'management',
  'weight' => '5',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'View reports, updates, and errors.',
    ),
  ),
  'router_path' => 'admin/reports',
  'parent_identifier' => '713f7554ad180f9b7c569b7e4c1cb974c931e048',
);

$dependencies = array(
  'menu_link.713f7554ad180f9b7c569b7e4c1cb974c931e048' => 'menu_link.713f7554ad180f9b7c569b7e4c1cb974c931e048',
);

$optional = array();

$modules = array();
