<?php
/**
 * @file
 * menu_link.5440005a9acc41ae6ea0335a022797c71396bfe5.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/user-interface',
  'link_title' => 'User interface',
  'menu_name' => 'management',
  'weight' => '-15',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Tools that enhance the user interface.',
    ),
  ),
  'router_path' => 'admin/config/user-interface',
  'parent_identifier' => '981d1362cf2de95e180c0b90045770044c40adc6',
);

$dependencies = array(
  'menu_link.981d1362cf2de95e180c0b90045770044c40adc6' => 'menu_link.981d1362cf2de95e180c0b90045770044c40adc6',
);

$optional = array();

$modules = array();
