<?php
/**
 * @file
 * menu_link.5f72395ffea955a81bec5747b1cb81ec0af239e5.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/reports/search',
  'link_title' => 'Top search phrases',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'View most popular search phrases.',
    ),
  ),
  'router_path' => 'admin/reports/search',
  'parent_identifier' => '6e9b944c771415a0ccba38da3b419ea22c255640',
);

$dependencies = array(
  'menu_link.6e9b944c771415a0ccba38da3b419ea22c255640' => 'menu_link.6e9b944c771415a0ccba38da3b419ea22c255640',
);

$optional = array();

$modules = array();
