<?php
/**
 * @file
 * menu_link.fbbf1fc5adef235eb72f55cb577ddec7648f31c9.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/services/oauth',
  'link_title' => 'OAuth',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Settings for OAuth',
    ),
  ),
  'router_path' => 'admin/config/services/oauth',
  'parent_identifier' => 'e4bf90832226d3be755b8c7e87c6b242beaeedb8',
);

$dependencies = array(
  'menu_link.e4bf90832226d3be755b8c7e87c6b242beaeedb8' => 'menu_link.e4bf90832226d3be755b8c7e87c6b242beaeedb8',
);

$optional = array();

$modules = array();
