<?php
/**
 * @file
 * menu_link.35d28b43f5615f0bbf4e743b32daa69f2c5bb62e.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/reports/page-not-found',
  'link_title' => 'Top \'page not found\' errors',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'View \'page not found\' errors (404s).',
    ),
  ),
  'router_path' => 'admin/reports/page-not-found',
  'parent_identifier' => '6e9b944c771415a0ccba38da3b419ea22c255640',
);

$dependencies = array(
  'menu_link.6e9b944c771415a0ccba38da3b419ea22c255640' => 'menu_link.6e9b944c771415a0ccba38da3b419ea22c255640',
);

$optional = array();

$modules = array();
