<?php
/**
 * @file
 * menu_link.14dd2d4a8a08215f40b4aa478529b344dfb8867f.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/people/accounts',
  'link_title' => 'Account settings',
  'menu_name' => 'management',
  'weight' => '-10',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Configure default behavior of users, including registration requirements, e-mails, fields, and user pictures.',
    ),
  ),
  'router_path' => 'admin/config/people/accounts',
  'parent_identifier' => '6731780bf1c905642eb264a8d3118ec57831fa15',
);

$dependencies = array(
  'menu_link.6731780bf1c905642eb264a8d3118ec57831fa15' => 'menu_link.6731780bf1c905642eb264a8d3118ec57831fa15',
);

$optional = array();

$modules = array();
