<?php
/**
 * @file
 * menu_link.ec0ed91b83aa344a476734142a6914e14fc7fbd5.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/regional/translate',
  'link_title' => 'Translate interface',
  'menu_name' => 'management',
  'weight' => '-5',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Translate the built in interface and optionally other text.',
    ),
  ),
  'router_path' => 'admin/config/regional/translate',
  'parent_identifier' => '29a0beace8faac4356003f60d9b4c5feb87d38f3',
);

$dependencies = array(
  'menu_link.29a0beace8faac4356003f60d9b4c5feb87d38f3' => 'menu_link.29a0beace8faac4356003f60d9b4c5feb87d38f3',
);

$optional = array();

$modules = array();
