<?php
/**
 * @file
 * menu_link.ef0082661602f85e5c700d4bd929cfa3db5d543f.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/search',
  'link_title' => 'Search and metadata',
  'menu_name' => 'management',
  'weight' => '-10',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Local site search, metadata and SEO.',
    ),
  ),
  'router_path' => 'admin/config/search',
  'parent_identifier' => '981d1362cf2de95e180c0b90045770044c40adc6',
);

$dependencies = array(
  'menu_link.981d1362cf2de95e180c0b90045770044c40adc6' => 'menu_link.981d1362cf2de95e180c0b90045770044c40adc6',
);

$optional = array();

$modules = array();
