<?php
/**
 * @file
 * menu_link.bd2adb5ed940bf03f1dd83d7d7be9e6f5d5fd755.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/people/ip-blocking',
  'link_title' => 'IP address blocking',
  'menu_name' => 'management',
  'weight' => '10',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Manage blocked IP addresses.',
    ),
  ),
  'router_path' => 'admin/config/people/ip-blocking',
  'parent_identifier' => '6731780bf1c905642eb264a8d3118ec57831fa15',
);

$dependencies = array(
  'menu_link.6731780bf1c905642eb264a8d3118ec57831fa15' => 'menu_link.6731780bf1c905642eb264a8d3118ec57831fa15',
);

$optional = array();

$modules = array();
