<?php
/**
 * @file
 * menu_link.113508ddc775310e8be23b6e1ae73c50ec8ff4a6.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/help',
  'link_title' => 'Help',
  'menu_name' => 'management',
  'weight' => '9',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Reference for usage, configuration, and modules.',
    ),
  ),
  'router_path' => 'admin/help',
  'parent_identifier' => '713f7554ad180f9b7c569b7e4c1cb974c931e048',
);

$dependencies = array(
  'menu_link.713f7554ad180f9b7c569b7e4c1cb974c931e048' => 'menu_link.713f7554ad180f9b7c569b7e4c1cb974c931e048',
);

$optional = array();

$modules = array();
