<?php
/**
 * @file
 * menu_link.efd5e02bf835a53228925c352c559ae74624d43e.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/workflow/rules',
  'link_title' => 'Rules',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Manage reaction rules and rule components.',
    ),
  ),
  'router_path' => 'admin/config/workflow/rules',
  'parent_identifier' => '1cf7f51f65269905dde8a74fac5c14380fdeedd7',
);

$dependencies = array(
  'menu_link.1cf7f51f65269905dde8a74fac5c14380fdeedd7' => 'menu_link.1cf7f51f65269905dde8a74fac5c14380fdeedd7',
);

$optional = array();

$modules = array();
