<?php
/**
 * @file
 * menu_link.dcfd3146ef8f38a8e39922aa56e2a5bb277a05e5.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/structure/menu/manage/main-menu',
  'link_title' => 'Main menu',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(),
  'router_path' => 'admin/structure/menu/manage/%',
  'parent_identifier' => '3111902c1834b75b83b11362f105c436d64db94a',
);

$dependencies = array(
  'menu_link.3111902c1834b75b83b11362f105c436d64db94a' => 'menu_link.3111902c1834b75b83b11362f105c436d64db94a',
);

$optional = array();

$modules = array();
