<?php
/**
 * @file
 * menu_link.1f289b5218d987821a6a9cb06b43b16714686244.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/system/configuration',
  'link_title' => 'Configuration Management',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Configuration Management',
    ),
  ),
  'router_path' => 'admin/config/system/configuration',
  'parent_identifier' => '4e354a16bb1634106a3ada7d78189d4d30588ae6',
);

$dependencies = array(
  'menu_link.4e354a16bb1634106a3ada7d78189d4d30588ae6' => 'menu_link.4e354a16bb1634106a3ada7d78189d4d30588ae6',
);

$optional = array();

$modules = array();
