<?php
/**
 * @file
 * menu_link.963da436e7470f5a21a45f472c8811b6107eaede.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/development/maintenance',
  'link_title' => 'Maintenance mode',
  'menu_name' => 'management',
  'weight' => '-10',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Take the site offline for maintenance or bring it back online.',
    ),
  ),
  'router_path' => 'admin/config/development/maintenance',
  'parent_identifier' => '85036b299694ce25b3be992e83036f020ee9651d',
);

$dependencies = array(
  'menu_link.85036b299694ce25b3be992e83036f020ee9651d' => 'menu_link.85036b299694ce25b3be992e83036f020ee9651d',
);

$optional = array();

$modules = array();
