<?php
/**
 * @file
 * menu_link.930a56d75af0957cb147eb4430d7ec487e517dce.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/reports/dblog',
  'link_title' => 'Recent log messages',
  'menu_name' => 'management',
  'weight' => '-1',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'View events that have recently been logged.',
    ),
  ),
  'router_path' => 'admin/reports/dblog',
  'parent_identifier' => '6e9b944c771415a0ccba38da3b419ea22c255640',
);

$dependencies = array(
  'menu_link.6e9b944c771415a0ccba38da3b419ea22c255640' => 'menu_link.6e9b944c771415a0ccba38da3b419ea22c255640',
);

$optional = array();

$modules = array();
