<?php
/**
 * @file
 * menu_link.29a0beace8faac4356003f60d9b4c5feb87d38f3.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/regional',
  'link_title' => 'Regional and language',
  'menu_name' => 'management',
  'weight' => '-5',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Regional settings, localization and translation.',
    ),
  ),
  'router_path' => 'admin/config/regional',
  'parent_identifier' => '981d1362cf2de95e180c0b90045770044c40adc6',
);

$dependencies = array(
  'menu_link.981d1362cf2de95e180c0b90045770044c40adc6' => 'menu_link.981d1362cf2de95e180c0b90045770044c40adc6',
);

$optional = array();

$modules = array();
