<?php
/**
 * @file
 * menu_link.3e85419840bf0dc7fa96340ad2f657cf6fb19cd3.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'node/add/page',
  'link_title' => 'Basic page',
  'menu_name' => 'navigation',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Use <em>basic pages</em> for your static content, such as an \'About us\' page.',
    ),
  ),
  'router_path' => 'node/add/page',
  'parent_identifier' => '7fa6a77950f9dfec910f197544505e3fb2f92723',
);

$dependencies = array(
  'menu_link.7fa6a77950f9dfec910f197544505e3fb2f92723' => 'menu_link.7fa6a77950f9dfec910f197544505e3fb2f92723',
);

$optional = array();

$modules = array();
