<?php
/**
 * @file
 * menu_link.8fd59a4b28d116ab5f3892dd6b42aa824a6fa72c.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/content/formats',
  'link_title' => 'Text formats',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Configure how content input by users is filtered, including allowed HTML tags. Also allows enabling of module-provided filters.',
    ),
  ),
  'router_path' => 'admin/config/content/formats',
  'parent_identifier' => '0abfc766397248b728a2eb15b845fda3aa5aefff',
);

$dependencies = array(
  'menu_link.0abfc766397248b728a2eb15b845fda3aa5aefff' => 'menu_link.0abfc766397248b728a2eb15b845fda3aa5aefff',
);

$optional = array();

$modules = array();
