<?php
/**
 * @file
 * menu_link.3c1bdfc88bf4d096e47098c88af765548c0535e5.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/reports/status',
  'link_title' => 'Status report',
  'menu_name' => 'management',
  'weight' => '-60',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Get a status report about your site\'s operation and any detected problems.',
    ),
  ),
  'router_path' => 'admin/reports/status',
  'parent_identifier' => '6e9b944c771415a0ccba38da3b419ea22c255640',
);

$dependencies = array(
  'menu_link.6e9b944c771415a0ccba38da3b419ea22c255640' => 'menu_link.6e9b944c771415a0ccba38da3b419ea22c255640',
);

$optional = array();

$modules = array();
