<?php
/**
 * @file
 * menu_link.875881f8912c89ded9cf9b2be19f3c00436a73ff.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'filter/tips',
  'link_title' => 'Compose tips',
  'menu_name' => 'navigation',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(),
  'router_path' => 'filter/tips',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.navigation' => 'menu.navigation',
);

$optional = array();

$modules = array();
