<?php
/**
 * @file
 * menu_link.294696088ac4bfe7cfaab64b4a50a83338bb6048.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/reports/updates',
  'link_title' => 'Available updates',
  'menu_name' => 'management',
  'weight' => '-50',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Get a status report about available updates for your installed modules and themes.',
    ),
  ),
  'router_path' => 'admin/reports/updates',
  'parent_identifier' => '6e9b944c771415a0ccba38da3b419ea22c255640',
);

$dependencies = array(
  'menu_link.6e9b944c771415a0ccba38da3b419ea22c255640' => 'menu_link.6e9b944c771415a0ccba38da3b419ea22c255640',
);

$optional = array();

$modules = array();
