<?php
/**
 * @file
 * menu_link.4e354a16bb1634106a3ada7d78189d4d30588ae6.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/system',
  'link_title' => 'System',
  'menu_name' => 'management',
  'weight' => '-20',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'General system related configuration.',
    ),
  ),
  'router_path' => 'admin/config/system',
  'parent_identifier' => '981d1362cf2de95e180c0b90045770044c40adc6',
);

$dependencies = array(
  'menu_link.981d1362cf2de95e180c0b90045770044c40adc6' => 'menu_link.981d1362cf2de95e180c0b90045770044c40adc6',
);

$optional = array();

$modules = array();
