<?php
/**
 * @file
 * menu_link.d306a9649efe328ae1293ec0d30b65095140a761.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/content/comment',
  'link_title' => 'Comments',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'List and edit site comments and the comment approval queue.',
    ),
  ),
  'router_path' => 'admin/content/comment',
  'parent_identifier' => 'c43a58aeada3d70ae9f892c266f3a54854394950',
);

$dependencies = array(
  'menu_link.c43a58aeada3d70ae9f892c266f3a54854394950' => 'menu_link.c43a58aeada3d70ae9f892c266f3a54854394950',
);

$optional = array();

$modules = array();
