<?php
/**
 * @file
 * menu_link.0abfc766397248b728a2eb15b845fda3aa5aefff.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/content',
  'link_title' => 'Content authoring',
  'menu_name' => 'management',
  'weight' => '-15',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Settings related to formatting and authoring content.',
    ),
  ),
  'router_path' => 'admin/config/content',
  'parent_identifier' => '981d1362cf2de95e180c0b90045770044c40adc6',
);

$dependencies = array(
  'menu_link.981d1362cf2de95e180c0b90045770044c40adc6' => 'menu_link.981d1362cf2de95e180c0b90045770044c40adc6',
);

$optional = array();

$modules = array();
