<?php
/**
 * @file
 * menu_link.3111902c1834b75b83b11362f105c436d64db94a.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/structure/menu',
  'link_title' => 'Menus',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Add new menus to your site, edit existing menus, and rename and reorganize menu links.',
    ),
  ),
  'router_path' => 'admin/structure/menu',
  'parent_identifier' => '9866f27a9b57b4c9309f2a33b11f318c4b6c852e',
);

$dependencies = array(
  'menu_link.9866f27a9b57b4c9309f2a33b11f318c4b6c852e' => 'menu_link.9866f27a9b57b4c9309f2a33b11f318c4b6c852e',
);

$optional = array();

$modules = array();
