<?php
/**
 * @file
 * menu_link.bed72455bb32d3cf5f89e07a3ea5738367e97677.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/system/actions',
  'link_title' => 'Actions',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Manage the actions defined for your site.',
    ),
  ),
  'router_path' => 'admin/config/system/actions',
  'parent_identifier' => '4e354a16bb1634106a3ada7d78189d4d30588ae6',
);

$dependencies = array(
  'menu_link.4e354a16bb1634106a3ada7d78189d4d30588ae6' => 'menu_link.4e354a16bb1634106a3ada7d78189d4d30588ae6',
);

$optional = array();

$modules = array();
