<?php
/**
 * @file
 * menu_link.ec9e13c9b2b1bf624aa9996d3049bfe6a120ff51.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/development/performance',
  'link_title' => 'Performance',
  'menu_name' => 'management',
  'weight' => '-20',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Enable or disable page caching for anonymous users and set CSS and JS bandwidth optimization options.',
    ),
  ),
  'router_path' => 'admin/config/development/performance',
  'parent_identifier' => '85036b299694ce25b3be992e83036f020ee9651d',
);

$dependencies = array(
  'menu_link.85036b299694ce25b3be992e83036f020ee9651d' => 'menu_link.85036b299694ce25b3be992e83036f020ee9651d',
);

$optional = array();

$modules = array();
