<?php
/**
 * @file
 * menu_link.191d6efc19a803c313d963b4fa2610245f1fa41a.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/regional/date-time',
  'link_title' => 'Date and time',
  'menu_name' => 'management',
  'weight' => '-15',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Configure display formats for date and time.',
    ),
  ),
  'router_path' => 'admin/config/regional/date-time',
  'parent_identifier' => '29a0beace8faac4356003f60d9b4c5feb87d38f3',
);

$dependencies = array(
  'menu_link.29a0beace8faac4356003f60d9b4c5feb87d38f3' => 'menu_link.29a0beace8faac4356003f60d9b4c5feb87d38f3',
);

$optional = array();

$modules = array();
