<?php
/**
 * @file
 * menu_link.7207b43a4259243a0ef47ad09aa589cebf454ca1.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/appearance',
  'link_title' => 'Appearance',
  'menu_name' => 'management',
  'weight' => '-6',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Select and configure your themes.',
    ),
  ),
  'router_path' => 'admin/appearance',
  'parent_identifier' => '713f7554ad180f9b7c569b7e4c1cb974c931e048',
);

$dependencies = array(
  'menu_link.713f7554ad180f9b7c569b7e4c1cb974c931e048' => 'menu_link.713f7554ad180f9b7c569b7e4c1cb974c931e048',
);

$optional = array();

$modules = array();
