<?php
/**
 * @file
 * menu_link.ec57a66ad3ae2ac9a13a1ad2a1218245f558b7de.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/search/path',
  'link_title' => 'URL aliases',
  'menu_name' => 'management',
  'weight' => '-5',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Change your site\'s URL paths by aliasing them.',
    ),
  ),
  'router_path' => 'admin/config/search/path',
  'parent_identifier' => 'ef0082661602f85e5c700d4bd929cfa3db5d543f',
);

$dependencies = array(
  'menu_link.ef0082661602f85e5c700d4bd929cfa3db5d543f' => 'menu_link.ef0082661602f85e5c700d4bd929cfa3db5d543f',
);

$optional = array();

$modules = array();
