<?php
/**
 * @file
 * menu_link.41544fde5c76cd2aed7b3a8cdd906e0e83f172f5.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/development/logging',
  'link_title' => 'Logging and errors',
  'menu_name' => 'management',
  'weight' => '-15',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Settings for logging and alerts modules. Various modules can route Drupal\'s system events to different destinations, such as syslog, database, email, etc.',
    ),
  ),
  'router_path' => 'admin/config/development/logging',
  'parent_identifier' => '85036b299694ce25b3be992e83036f020ee9651d',
);

$dependencies = array(
  'menu_link.85036b299694ce25b3be992e83036f020ee9651d' => 'menu_link.85036b299694ce25b3be992e83036f020ee9651d',
);

$optional = array();

$modules = array();
