<?php
/**
 * @file
 * menu_link.5be5a81838daaa1b9e94c7182e24343f9ea63629.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/media/image-styles',
  'link_title' => 'Image styles',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Configure styles that can be used for resizing or adjusting images on display.',
    ),
  ),
  'router_path' => 'admin/config/media/image-styles',
  'parent_identifier' => 'a0ac7769dd155924a164eb528a16bc61c42033cf',
);

$dependencies = array(
  'menu_link.a0ac7769dd155924a164eb528a16bc61c42033cf' => 'menu_link.a0ac7769dd155924a164eb528a16bc61c42033cf',
);

$optional = array();

$modules = array();
