<?php
/**
 * @file
 * menu_link.11c6040c933285c023b20607493d3aeb663b5948.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/structure/block',
  'link_title' => 'Blocks',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Configure what block content appears in your site\'s sidebars and other regions.',
    ),
  ),
  'router_path' => 'admin/structure/block',
  'parent_identifier' => '9866f27a9b57b4c9309f2a33b11f318c4b6c852e',
);

$dependencies = array(
  'menu_link.9866f27a9b57b4c9309f2a33b11f318c4b6c852e' => 'menu_link.9866f27a9b57b4c9309f2a33b11f318c4b6c852e',
);

$optional = array();

$modules = array();
