<?php
/**
 * @file
 * menu_link.3b87f96525aa5132103c5e6c13b4655eae5e1e9f.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/regional/language',
  'link_title' => 'Languages',
  'menu_name' => 'management',
  'weight' => '-10',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Configure languages for content and the user interface.',
    ),
  ),
  'router_path' => 'admin/config/regional/language',
  'parent_identifier' => '29a0beace8faac4356003f60d9b4c5feb87d38f3',
);

$dependencies = array(
  'menu_link.29a0beace8faac4356003f60d9b4c5feb87d38f3' => 'menu_link.29a0beace8faac4356003f60d9b4c5feb87d38f3',
);

$optional = array();

$modules = array();
