<?php
/**
 * @file
 * menu_link.66bd4b99ca85c44f685ca90ae6a6bb9a8412bbe3.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/services/wsclient',
  'link_title' => 'Web service descriptions',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Manage Web Service Descriptions for Web service client.',
    ),
  ),
  'router_path' => 'admin/config/services/wsclient',
  'parent_identifier' => 'e4bf90832226d3be755b8c7e87c6b242beaeedb8',
);

$dependencies = array(
  'menu_link.e4bf90832226d3be755b8c7e87c6b242beaeedb8' => 'menu_link.e4bf90832226d3be755b8c7e87c6b242beaeedb8',
);

$optional = array();

$modules = array();
