<?php
/**
 * @file
 * menu_link.6731780bf1c905642eb264a8d3118ec57831fa15.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/people',
  'link_title' => 'People',
  'menu_name' => 'management',
  'weight' => '-20',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Configure user accounts.',
    ),
  ),
  'router_path' => 'admin/config/people',
  'parent_identifier' => '981d1362cf2de95e180c0b90045770044c40adc6',
);

$dependencies = array(
  'menu_link.981d1362cf2de95e180c0b90045770044c40adc6' => 'menu_link.981d1362cf2de95e180c0b90045770044c40adc6',
);

$optional = array();

$modules = array();
