<?php
/**
 * @file
 * menu_link.366668a25073d7909919d71d58d20fecc230e5c3.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/services/rss-publishing',
  'link_title' => 'RSS publishing',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Configure the site description, the number of items per feed and whether feeds should be titles/teasers/full-text.',
    ),
  ),
  'router_path' => 'admin/config/services/rss-publishing',
  'parent_identifier' => 'e4bf90832226d3be755b8c7e87c6b242beaeedb8',
);

$dependencies = array(
  'menu_link.e4bf90832226d3be755b8c7e87c6b242beaeedb8' => 'menu_link.e4bf90832226d3be755b8c7e87c6b242beaeedb8',
);

$optional = array();

$modules = array();
