<?php
/**
 * @file
 * menu_link.a9380395a4064a157f2162df746cea9a95299e6e.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/search/settings',
  'link_title' => 'Search settings',
  'menu_name' => 'management',
  'weight' => '-10',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Configure relevance settings for search and other indexing options.',
    ),
  ),
  'router_path' => 'admin/config/search/settings',
  'parent_identifier' => 'ef0082661602f85e5c700d4bd929cfa3db5d543f',
);

$dependencies = array(
  'menu_link.ef0082661602f85e5c700d4bd929cfa3db5d543f' => 'menu_link.ef0082661602f85e5c700d4bd929cfa3db5d543f',
);

$optional = array();

$modules = array();
