<?php
/**
 * @file
 * menu_link.85036b299694ce25b3be992e83036f020ee9651d.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/development',
  'link_title' => 'Development',
  'menu_name' => 'management',
  'weight' => '-10',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Development tools.',
    ),
  ),
  'router_path' => 'admin/config/development',
  'parent_identifier' => '981d1362cf2de95e180c0b90045770044c40adc6',
);

$dependencies = array(
  'menu_link.981d1362cf2de95e180c0b90045770044c40adc6' => 'menu_link.981d1362cf2de95e180c0b90045770044c40adc6',
);

$optional = array();

$modules = array();
