<?php
/**
 * @file
 * menu_link.c43a58aeada3d70ae9f892c266f3a54854394950.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/content',
  'link_title' => 'Content',
  'menu_name' => 'management',
  'weight' => '-10',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Administer content and comments.',
    ),
  ),
  'router_path' => 'admin/content',
  'parent_identifier' => '713f7554ad180f9b7c569b7e4c1cb974c931e048',
);

$dependencies = array(
  'menu_link.713f7554ad180f9b7c569b7e4c1cb974c931e048' => 'menu_link.713f7554ad180f9b7c569b7e4c1cb974c931e048',
);

$optional = array();

$modules = array();
