<?php
/**
 * @file
 * menu_link.e00778603f5d2fb1dd472b9463d1c805d02c2c47.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/user-interface/shortcut',
  'link_title' => 'Shortcuts',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Add and modify shortcut sets.',
    ),
  ),
  'router_path' => 'admin/config/user-interface/shortcut',
  'parent_identifier' => '5440005a9acc41ae6ea0335a022797c71396bfe5',
);

$dependencies = array(
  'menu_link.5440005a9acc41ae6ea0335a022797c71396bfe5' => 'menu_link.5440005a9acc41ae6ea0335a022797c71396bfe5',
);

$optional = array();

$modules = array();
