<?php
/**
 * @file
 * menu_link.0c9a1001ea3cd54923d2f1d0a7f88418f7c4a66e.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/structure/types',
  'link_title' => 'Content types',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Manage content types, including default status, front page promotion, comment settings, etc.',
    ),
  ),
  'router_path' => 'admin/structure/types',
  'parent_identifier' => '9866f27a9b57b4c9309f2a33b11f318c4b6c852e',
);

$dependencies = array(
  'menu_link.9866f27a9b57b4c9309f2a33b11f318c4b6c852e' => 'menu_link.9866f27a9b57b4c9309f2a33b11f318c4b6c852e',
);

$optional = array();

$modules = array();
