<?php
/**
 * @file
 * menu_link.91ded59d3f4e7c199586cca99b952565d9d37166.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/system/cron',
  'link_title' => 'Cron',
  'menu_name' => 'management',
  'weight' => '20',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Manage automatic site maintenance tasks.',
    ),
  ),
  'router_path' => 'admin/config/system/cron',
  'parent_identifier' => '4e354a16bb1634106a3ada7d78189d4d30588ae6',
);

$dependencies = array(
  'menu_link.4e354a16bb1634106a3ada7d78189d4d30588ae6' => 'menu_link.4e354a16bb1634106a3ada7d78189d4d30588ae6',
);

$optional = array();

$modules = array();
