<?php
/**
 * @file
 * menu_link.17820cafa2a3f013d4b916a340a6f7658dbe5851.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/people',
  'link_title' => 'People',
  'menu_name' => 'management',
  'weight' => '-4',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Manage user accounts, roles, and permissions.',
    ),
  ),
  'router_path' => 'admin/people',
  'parent_identifier' => '713f7554ad180f9b7c569b7e4c1cb974c931e048',
);

$dependencies = array(
  'menu_link.713f7554ad180f9b7c569b7e4c1cb974c931e048' => 'menu_link.713f7554ad180f9b7c569b7e4c1cb974c931e048',
);

$optional = array();

$modules = array();
