<?php
/**
 * @file
 * menu_link.fc486f9fbc01dc672df92bb08cc4681c5c7dc011.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/reports/access-denied',
  'link_title' => 'Top \'access denied\' errors',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'View \'access denied\' errors (403s).',
    ),
  ),
  'router_path' => 'admin/reports/access-denied',
  'parent_identifier' => '6e9b944c771415a0ccba38da3b419ea22c255640',
);

$dependencies = array(
  'menu_link.6e9b944c771415a0ccba38da3b419ea22c255640' => 'menu_link.6e9b944c771415a0ccba38da3b419ea22c255640',
);

$optional = array();

$modules = array();
