<?php
/**
 * @file
 * menu_link.517df4132b2f110d38cbf4c8090960858ad683b4.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/reports/fields',
  'link_title' => 'Field list',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Overview of fields on all entity types.',
    ),
  ),
  'router_path' => 'admin/reports/fields',
  'parent_identifier' => '6e9b944c771415a0ccba38da3b419ea22c255640',
);

$dependencies = array(
  'menu_link.6e9b944c771415a0ccba38da3b419ea22c255640' => 'menu_link.6e9b944c771415a0ccba38da3b419ea22c255640',
);

$optional = array();

$modules = array();
