<?php
/**
 * @file
 * menu_link.713f7554ad180f9b7c569b7e4c1cb974c931e048.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin',
  'link_title' => 'Administration',
  'menu_name' => 'management',
  'weight' => '9',
  'expanded' => '0',
  'options' => array(),
  'router_path' => 'admin',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.management' => 'menu.management',
);

$optional = array();

$modules = array();
