<?php
/**
 * @file
 * menu_link.23c6cde2c9a090214b08ec4498cf292515a5d4cd.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'node/add/article',
  'link_title' => 'Article',
  'menu_name' => 'navigation',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Use <em>articles</em> for time-sensitive content like news, press releases or blog posts.',
    ),
  ),
  'router_path' => 'node/add/article',
  'parent_identifier' => '7fa6a77950f9dfec910f197544505e3fb2f92723',
);

$dependencies = array(
  'menu_link.7fa6a77950f9dfec910f197544505e3fb2f92723' => 'menu_link.7fa6a77950f9dfec910f197544505e3fb2f92723',
);

$optional = array();

$modules = array();
