<?php
/**
 * @file
 * menu_link.b2589d4113174a375674ea819f80f20b6c59545f.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/media/image-toolkit',
  'link_title' => 'Image toolkit',
  'menu_name' => 'management',
  'weight' => '20',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Choose which image toolkit to use if you have installed optional toolkits.',
    ),
  ),
  'router_path' => 'admin/config/media/image-toolkit',
  'parent_identifier' => 'a0ac7769dd155924a164eb528a16bc61c42033cf',
);

$dependencies = array(
  'menu_link.a0ac7769dd155924a164eb528a16bc61c42033cf' => 'menu_link.a0ac7769dd155924a164eb528a16bc61c42033cf',
);

$optional = array();

$modules = array();
