<?php
/**
 * @file
 * menu_link.1d763ec92b4f56a1634dee6b0cdf70792ba36f1f.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'search',
  'link_title' => 'Search',
  'menu_name' => 'navigation',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(),
  'router_path' => 'search',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.navigation' => 'menu.navigation',
);

$optional = array();

$modules = array();
