<?php
/**
 * @file
 * menu_link.b9de1899a920ba86e8fe41e4394b9048dfe2781c.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/dashboard',
  'link_title' => 'Dashboard',
  'menu_name' => 'management',
  'weight' => '-15',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'View and customize your dashboard.',
    ),
  ),
  'router_path' => 'admin/dashboard',
  'parent_identifier' => '713f7554ad180f9b7c569b7e4c1cb974c931e048',
);

$dependencies = array(
  'menu_link.713f7554ad180f9b7c569b7e4c1cb974c931e048' => 'menu_link.713f7554ad180f9b7c569b7e4c1cb974c931e048',
);

$optional = array();

$modules = array();
