<?php
/**
 * @file
 * menu_link.edb77481ef591813f850ea5275b6726295304edb.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/structure/taxonomy',
  'link_title' => 'Taxonomy',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Manage tagging, categorization, and classification of your content.',
    ),
  ),
  'router_path' => 'admin/structure/taxonomy',
  'parent_identifier' => '9866f27a9b57b4c9309f2a33b11f318c4b6c852e',
);

$dependencies = array(
  'menu_link.9866f27a9b57b4c9309f2a33b11f318c4b6c852e' => 'menu_link.9866f27a9b57b4c9309f2a33b11f318c4b6c852e',
);

$optional = array();

$modules = array();
