<?php
/**
 * @file
 * permission.use_text_format_full_html_plain_no_filter_.inc
 */

$api = '2.0.0';

$data = array(
  'permission' => 'use text format full_html_plain_no_filter_',
  'roles' => array(
    0 => 'administrator',
  ),
);

$dependencies = array(
  'text_format.full_html_plain_no_filter_' => 'text_format.full_html_plain_no_filter_',
);

$optional = array();

$modules = array(
  0 => 'filter',
);
