<?php
/**
 * @file
 * variable.javascript_parsed.inc
 */

$api = '2.0.0';

$data = array(
  'name' => 'javascript_parsed',
  'content' => array(
    0 => 'misc/drupal.js',
    1 => 'misc/jquery.js',
    2 => 'misc/jquery.once.js',
    3 => 'misc/tableheader.js',
    4 => 'misc/form.js',
    5 => 'misc/collapse.js',
    6 => 'misc/jquery.cookie.js',
    7 => 'modules/toolbar/toolbar.js',
    8 => 'misc/vertical-tabs.js',
    9 => 'sites/all/modules/configuration/ui/js/configuration_ui.js',
    10 => 'misc/tableselect.js',
    11 => 'sites/all/modules/configuration/ui/theme/vertical-tabs.js',
    12 => 'misc/textarea.js',
  ),
);

$dependencies = array();

$optional = array();

$modules = array();
