<?php
/**
 * @file
 * variable.menu_masks.inc
 */

$api = '2.0.0';

$data = $strongarm = new stdClass();
$strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
$strongarm->api_version = 1;
$strongarm->name = 'menu_masks';
$strongarm->value = array(
  0 => 507,
  1 => 506,
  2 => 501,
  3 => 493,
  4 => 490,
  5 => 255,
  6 => 253,
  7 => 252,
  8 => 251,
  9 => 250,
  10 => 247,
  11 => 246,
  12 => 245,
  13 => 242,
  14 => 241,
  15 => 238,
  16 => 234,
  17 => 127,
  18 => 126,
  19 => 125,
  20 => 124,
  21 => 123,
  22 => 122,
  23 => 121,
  24 => 120,
  25 => 119,
  26 => 117,
  27 => 116,
  28 => 63,
  29 => 62,
  30 => 61,
  31 => 60,
  32 => 59,
  33 => 58,
  34 => 56,
  35 => 45,
  36 => 44,
  37 => 31,
  38 => 30,
  39 => 29,
  40 => 28,
  41 => 27,
  42 => 26,
  43 => 24,
  44 => 23,
  45 => 22,
  46 => 21,
  47 => 15,
  48 => 14,
  49 => 13,
  50 => 12,
  51 => 11,
  52 => 10,
  53 => 8,
  54 => 7,
  55 => 6,
  56 => 5,
  57 => 3,
  58 => 2,
  59 => 1,
);


$dependencies = array();

$optional = array();

$modules = array(
  0 => 'strongarm',
  1 => 'ctools',
  2 => 'system',
);
