<?php
/**
 * @file
 * variable.cron_key.inc
 */

$api = '2.0.0';

$data = $strongarm = new stdClass();
$strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
$strongarm->api_version = 1;
$strongarm->name = 'cron_key';
$strongarm->value = '3Xyblf79pYceDSEarhzRhq6fcplG_c3tqRtEBZAVKKU';


$dependencies = array();

$optional = array();

$modules = array(
  0 => 'strongarm',
  1 => 'ctools',
  2 => 'system',
);
