<?php
/**
 * @file
 * variable.variable_module_list.inc
 */

$api = '2.0.0';

$data = array(
  'name' => 'variable_module_list',
  'content' => array(
    'locale' => array(
      0 => 'language_content_type_article',
      1 => 'language_content_type_page',
      2 => 'language_default',
    ),
    'i18n' => array(
      0 => 'i18n_language_list',
    ),
    'i18n_string' => array(
      0 => 'i18n_string_translate_langcode_en',
      1 => 'i18n_string_allowed_formats',
      2 => 'i18n_string_source_language',
      3 => 'i18n_string_debug',
    ),
  ),
);

$dependencies = array();

$optional = array();

$modules = array();
