<?php
/*
 * Copyright (C) 2015
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 as published
 * by the Free Software Foundation.
 *
 * If the program is linked with libraries which are licensed under one of
 * the following licenses, the combination of the program with the linked
 * library is not considered a "derivative work" of the program:
 *
 *     - Apache License, version 2.0
 *     - Apache Software License, version 1.0
 *     - GNU Lesser General Public License, version 3
 *     - Mozilla Public License, versions 1.0, 1.1 and 2.0
 *     - Common Development and Distribution License (CDDL), version 1.0
 *
 * Therefore the distribution of the program linked with libraries licensed
 * under the aforementioned licenses, is permitted by the copyright holders
 * if the distribution is compliant with both the GNU General Public
 * License version 2 and the aforementioned licenses.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
 * Public License for more details.
 */
/**
 * Implement hook_form_alter to display information message for each content
 * type how the revision workflow works.
 * 
 */
function n52_revisioning_form_alter(&$form, &$form_state, $form_id) {
  if (n52_endsWith($form_id, '_node_form')) {
    $form['revision_information']['log']['#description'] =
      $form['revision_information']['log']['#description'] .
      '<div class="alert alert-info">' .
      t('Add "<i>ready to review</i>" to your revision log message to ' .
        'notify all moderators that your revision is ready for review.') .
      '</div>';
    $form['actions']['draft'] = array(
        '#type' => 'submit',
        '#value' => t('Save draft'),
        '#weight' => '9',
        '#submit' => array('n52_revisioning_save_draft_submit'),
        '#validate' => array('n52_revisioning_save_draft_validate'),
        '#attributes' => array(
            'class' => array('cancel'),
        ),
    );
  }
}

function n52_revisioning_save_draft_validate($form, &$form_state) {
  $form_state['values']['status'] = 0;
  $errors = &drupal_static('form_set_error', NULL, TRUE);
}

function n52_revisioning_save_draft_submit($form, &$form_state) {
  drupal_get_messages();
  node_form_submit($form, $form_state);
  $form_state['redirect'] = 'node/'.$form_state['nid'].'/edit';
}