<?php

/**
 * @file
 * Add support for entity reference field to be used with web service fields
 *
 * @author Mathew Winstone <mwinstone@coldfrontlabs.ca>
 */

/**
 * Implements hook_wsfields_FIELD_TYPE_data_alter().
 */
function ws_entityreference_wsfields_entityreference_data_alter($data, $field) {
  $field_data = array();

  if (!empty($field['translatable'])) {
    $languages = language_list();
  }
  else {
    $languages = array(LANGUAGE_NONE => LANGUAGE_NONE);
  }

  foreach($languages as $lang => $language) {
    foreach ($data[$lang] as $key => $lang_data) {
      $field_data[$lang][$key] = array('target_id' => $lang_data);
    }

  }

  $data = $field_data;
}
