<?php
/*
 * Copyright (C) 2015
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 as published
 * by the Free Software Foundation.
 *
 * If the program is linked with libraries which are licensed under one of
 * the following licenses, the combination of the program with the linked
 * library is not considered a "derivative work" of the program:
 *
 *     - Apache License, version 2.0
 *     - Apache Software License, version 1.0
 *     - GNU Lesser General Public License, version 3
 *     - Mozilla Public License, versions 1.0, 1.1 and 2.0
 *     - Common Development and Distribution License (CDDL), version 1.0
 *
 * Therefore the distribution of the program linked with libraries licensed
 * under the aforementioned licenses, is permitted by the copyright holders
 * if the distribution is compliant with both the GNU General Public
 * License version 2 and the aforementioned licenses.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
 * Public License for more details.
 */
/**
 * Implement hook_form_alter to display information message for each content
 * type how the revision workflow works.
 * 
 */
function n52_product_of_the_month_form_alter(&$form, &$form_state, $form_id) {
	if ($form_id === 'tool_node_form') {
		$form['options']['promote']['#title'] = 
			t('Product of the month');
		$form['options']['promote']['#weight'] = 40;
		$form['options']['promote_note'] = array(
        	'#type' => 'item',
        	'#description' => '<div class="alert alert-info">' . 
				t('Check this option to add this product to the "<i>product ' .
				'of the month</i>" block on the landing page. Only the ' .
				'<em>last</em> product published with this setting will ' .
				'be displayed.') .
				'</div>',
			'#weight' => 41,
		);
	}
}