<?php
/*
 * Copyright (C) 2015
 * 
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 as published
 * by the Free Software Foundation.
 * 
 * If the program is linked with libraries which are licensed under one of
 * the following licenses, the combination of the program with the linked
 * library is not considered a "derivative work" of the program:
 * 
 *     - Apache License, version 2.0
 *     - Apache Software License, version 1.0
 *     - GNU Lesser General Public License, version 3
 *     - Mozilla Public License, versions 1.0, 1.1 and 2.0
 *     - Common Development and Distribution License (CDDL), version 1.0
 * 
 * Therefore the distribution of the program linked with libraries licensed
 * under the aforementioned licenses, is permitted by the copyright holders
 * if the distribution is compliant with both the GNU General Public
 * License version 2 and the aforementioned licenses.
 * 
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
 * Public License for more details.
 */

// TODO add admin menu to change selector

/*
function n52_autocomplete_pre_render(&$view) {
	$display = 'page';
	if ($view->name == 'nodes-autocomplete' && $view->current_display == $display) {
		$other_view = views_get_view('users_autocomplete');
		$other_view->set_display($display);
		$other_view->execute();
		$view->result = array_merge($view->result, $other_view->result);
	}
}
*/

 /**
  * Implements hook_init().
  *
  * Add autocomplete.js on every page.
  */
function n52_autocomplete_page_build() {
	if (user_access('use Search Autocomplete')) {
		$settings = array ('n52_autocomplete' => array (
			'selector' => 'textarea'
		));
		drupal_add_js(drupal_get_path('module', 'n52_autocomplete') . '/js/jquery.autocomplete.js');
		drupal_add_js($settings, 'setting');
	}
}