<?php

/**
 * @file
 * The main file for quiz_h5p.
 */

/**
 * Implements hook_quiz_question_info().
 */
function quiz_h5p_quiz_question_info() {
  return array(
    'h5p_content' => array(
      'name' => t('H5P question'),
      'description' => t('Quiz questions using H5P. NOTE: It is possible for computer savvy users to cheat and submit a full score for a test without actually doing the test.'),
      'question provider' => 'QuizQuestionH5P',
      'response provider' => 'QuizQuestionH5PResponse',
      'node' => FALSE,
      'module' => 'quiz_question',
    ),
  );
}


/**
 * Implements hook_theme().
 */
function quiz_h5p_theme($existing, $type, $theme, $path) {
  $path = drupal_get_path('module', 'quiz_h5p') . '/theme';
  return array(
    'quiz_h5p_response' => array(
      'variables' => array(
        'data' => array(),
      ),
      'path' => $path,
      'file' => 'quiz_h5p.theme.inc',
    )
  );
}
