<?php

/**
 * @file
 * Image effect kit admin configuration.
 */

/*
function iek_admin_form() {
  $form = array();

  $form['watermark_fonts'] = array(
    '#type' => 'fieldset',
    '#title' => t('Watermark fonts'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#tree' => TRUE,
  );
  $form['watermark_fonts']['name'] = array(
    '#type' => 'textfield',
    '#title' => t('Name'),
    '#description' => '',
    '#maxlength' => 255,
    '#required' => TRUE,
  );
  $form['watermark_fonts']['title'] = array(
    '#type' => 'textfield',
    '#title' => t('Title'),
    '#description' => '',
    '#maxlength' => 255,
    '#required' => TRUE,
  );

  return $form;
}

function iek_admin_watermark_form() {

}
*/
