<?php

/**
 * @file
 * Defines core functionality for web service powered entities
 */

/**
 * Implements hook_permission().
 */
function wsentities_permission() {
  return array(
    'administer wsentities' =>  array(
      'title' => t('Administer Web Service Entities'),
      'description' => t('Perform administration tasks for Web Service Entities.'),
    ),
  );
}

/**
 *  Implements hook_menu().
 */
function wsentities_menu() {
  $items = array();

  return $items;
}
