<?php
/*
 * Copyright (C) 2015
 * 
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 as published
 * by the Free Software Foundation.
 * 
 * If the program is linked with libraries which are licensed under one of
 * the following licenses, the combination of the program with the linked
 * library is not considered a "derivative work" of the program:
 * 
 *     - Apache License, version 2.0
 *     - Apache Software License, version 1.0
 *     - GNU Lesser General Public License, version 3
 *     - Mozilla Public License, versions 1.0, 1.1 and 2.0
 *     - Common Development and Distribution License (CDDL), version 1.0
 * 
 * Therefore the distribution of the program linked with libraries licensed
 * under the aforementioned licenses, is permitted by the copyright holders
 * if the distribution is compliant with both the GNU General Public
 * License version 2 and the aforementioned licenses.
 * 
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
 * Public License for more details.
 */
/**
 * Implements hook_menu()
 * 
 * Link in default menu (e.g. Navigation)
 */
function n52_js_sos_client_menu() {
	$menu ['n52/jsClient'] = array (
			// page title
			'title' => 'View Client Reloaded',
			'page callback' => 'n52_js_sos_client_callback',
			'access arguments' => array (
					'access content',
			),
	);
	return $menu;
}

/**
 * The callback to integrate the js based application
 */
function n52_js_sos_client_callback() {
	$base_path = '/' . drupal_get_path('module', 'n52_js_sos_client') . '/';
	
	$page_contents =
			'<script type="text/javascript">' .
				'function n52CalcHeight() {' .
					// find the height of the internal page
					'var globalHeight = window.innerHeight || document.documentElement.clientHeight || document.body.clientHeight;' .
					'globalHeight = globalHeight - 375;' .
					// find height of content div (375 needs to be calculated in production environment)
					'var contentHeight = document.getElementById("page").offsetHeight;' .
					//change the height of the iframe
					'var iframe = document.getElementById("jsc-iframe");' .
					'iframe.style.height = globalHeight + "px";' .
				'}' .
				'window.onresize = function() {' .
					'n52CalcHeight();' .
				'}' .
			'</script>' .
			'<iframe ' . 
				'id="jsc-iframe" ' . 
				'onLoad="n52CalcHeight()" ' . 
				'src="' . $base_path . 'index.html" ' . 
				'style="width: 100%; border: none"></iframe>' .
			'<div id="height"></div>';
	
	$page_array = array ('#markup' => $page_contents);
	
	return $page_array;
}
