<?php

/**
 * @file
 */

/**
 * Implements hook_theme().
 */
function harmony_hide_user_theme($existing, $type, $theme, $path) {
  return array(
    'harmony_post_hidden' => array(
      'render element' => 'element',
    ),
  );
}

/**
 * Implements hook_entity_info_alter().
 */
function harmony_hide_user_entity_info_alter(&$entity_info) {
  // Add in a new view mode for "hidden".
  $entity_info['harmony_post']['view modes'] += array(
    'post_hidden' => array(
      'label' => t('Post hidden'),
      'custom settings' => FALSE,
    ),
  );
}

/**
 * Implements hook_entity_view_mode_alter().
 */
function harmony_hide_user_entity_view_mode_alter(&$view_mode, $context) {
  global $user;
  if ($user->uid && $context['entity_type'] === 'harmony_post' && $view_mode === 'full') {
    // Check to see if this post is by someone who this user wants hidden.
    $flag = flag_get_flag(variable_get('harmony_hide_user_flag_name', 'harmony_hide_user'));

    if ($flag && $flag->is_flagged($context['entity']->uid, $user->uid)) {
      $view_mode = 'post_hidden';
    }
  }
}

/**
 * Implements hook_harmony_post_view().
 */
function harmony_hide_user_harmony_post_view_alter(&$build, $type) {
  if ($build['#view_mode'] === 'post_hidden') {
    $build['#theme'] = 'harmony_post_hidden';
  }
}

/**
 * Theme callback.
 */
function theme_harmony_post_hidden($variables) {
  $post = $variables['element']['#post'];

  return '<div id="post-' . $post->post_id . '" class="post post-hidden">
    <a name="post-' . $post->post_id . '"></a>
    <div class="text-muted text-center text-small text-light-grey">' . t('This post has been hidden') . '</div>
  </div>';
}

/**
 * hook_flag_default_flags().
 */
function harmony_hide_user_flag_default_flags() {
  $flags = array();

  $flags['harmony_hide_user'] = array(
    'entity_type' => 'user',
    'title' => 'Hide user',
    'global' => 0,
    'types' => array(),
    'flag_short' => 'Hide user',
    'flag_long' => 'Hide this users content',
    'flag_message' => '',
    'unflag_short' => 'Unhide user',
    'unflag_long' => 'Unhide this users content',
    'unflag_message' => '',
    'unflag_denied_text' => '',
    'link_type' => 'toggle',
    'weight' => 0,
    'show_in_links' => array(
      'full' => 'full',
      'diff_standard' => 0,
      'harmony_user_post_profile' => 0,
      'token' => 0,
    ),
    'show_as_field' => 0,
    'show_on_form' => 0,
    'access_author' => '',
    'show_contextual_link' => FALSE,
    'show_on_profile' => 0,
    'access_uid' => 'others',
    'api_version' => 3,
  );

  return $flags;
}
