<?php
/*
 * Copyright (C) 2015
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 as published
 * by the Free Software Foundation.
 *
 * If the program is linked with libraries which are licensed under one of
 * the following licenses, the combination of the program with the linked
 * library is not considered a "derivative work" of the program:
 *
 *     - Apache License, version 2.0
 *     - Apache Software License, version 1.0
 *     - GNU Lesser General Public License, version 3
 *     - Mozilla Public License, versions 1.0, 1.1 and 2.0
 *     - Common Development and Distribution License (CDDL), version 1.0
 *
 * Therefore the distribution of the program linked with libraries licensed
 * under the aforementioned licenses, is permitted by the copyright holders
 * if the distribution is compliant with both the GNU General Public
 * License version 2 and the aforementioned licenses.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
 * Public License for more details.
 */
/**
 * Implements hook_from_FORM-ID_alter()
 *
 * Add advanced search link to search form pop-up
 */
function n52_advanced_search_block_view_alter(&$data, $block) {
	if (isset($data) && isset($data['content']) && isset($data['content']['form_id']) && isset($data['content']['form_id']['#value']) &&
			$data['content']['form_id']['#value'] == 'custom_search_blocks_form_1' &&
			isset($data['content']['popup'])) {
		$data['content']['popup']['link'] = array (
				'#markup' => l(t('Advanced Search'),'search/advanced'),
				// weight > 0 => link is display below content type checkboxes
				// weight <= 0 => link is displayed above content type checkboxes
				'#weight' => 0,
		);
	}
}
