<?php
/**
 * @file
 * harmony_atjs.features.features_overrides.inc
 */

/**
 * Implements hook_features_override_default_overrides().
 */
function harmony_atjs_features_override_default_overrides() {
  // This code is only used for UI in features. Exported alters hooks do the magic.
  $overrides = array();

  // Exported overrides for: field_instance

  // Exported overrides for: filter

 return $overrides;
}
