<?php
/*
 * Copyright (C) 2016
 * 
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 as published
 * by the Free Software Foundation.
 * 
 * If the program is linked with libraries which are licensed under one of
 * the following licenses, the combination of the program with the linked
 * library is not considered a "derivative work" of the program:
 * 
 *     - Apache License, version 2.0
 *     - Apache Software License, version 1.0
 *     - GNU Lesser General Public License, version 3
 *     - Mozilla Public License, versions 1.0, 1.1 and 2.0
 *     - Common Development and Distribution License (CDDL), version 1.0
 * 
 * Therefore the distribution of the program linked with libraries licensed
 * under the aforementioned licenses, is permitted by the copyright holders
 * if the distribution is compliant with both the GNU General Public
 * License version 2 and the aforementioned licenses.
 * 
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
 * Public License for more details.
 */
function n52_default_nodes_form_field_ui_field_overview_form_alter(&$form, &$form_state, $form_id){
	// iterate of fields in $form['fields']
	foreach ($form['fields'] as $key => $value) {
		// use everything not starting with '#'
		if (substr($key,0,1) === '#') {
			continue;
		}
		$field_name = $key;
		// use $form['fields']['field_n']['field_name'] to load field instance
		// check if required
		if (field_info_instance($form['#entity_type'], $field_name, $form['#bundle'])['required']) {
			// if required, update $form['fields']['field_n']['label']['#markup']
			// '<sup><b><span style="color: #f00;">*</span></b></sup>' . $form['fields']['field_n']['label']['#markup']
			$form['fields'][$field_name]['label']['#markup'] =
				'<sup><b><span style="color: #f00;">*</span></b></sup>' .
				$form['fields'][$field_name]['label']['#markup'];
		}
	}
}
