<?php
/**
 * @file
 * waterinneu_feature_projects.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function waterinneu_feature_projects_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "context" && $api == "context") {
    return array("version" => "3");
  }
  if ($module == "field_group" && $api == "field_group") {
    return array("version" => "1");
  }
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_views_api().
 */
function waterinneu_feature_projects_views_api($module = NULL, $api = NULL) {
  return array("api" => "3.0");
}

/**
 * Implements hook_node_info().
 */
function waterinneu_feature_projects_node_info() {
  $items = array(
    'project' => array(
      'name' => t('Project'),
      'base' => 'node_content',
      'description' => t('A project dealing with hydrological topics.'),
      'has_title' => '1',
      'title_label' => t('Name'),
      'help' => t('Project deletion is only possible by admins. If you want to have an project deleted, please use the <a href="/contact">contact form</a>.

Get in touch with our <a href="helpdeskt">helpdesk</a> if your content does not fit in this form.'),
    ),
  );
  drupal_alter('node_info', $items);
  return $items;
}
