<?php

/**
 * Run all update hooks.
 */

function randbee_e_learning_install_install() {
  for ($i = 7000; $i < 7200; $i++) {
    $candidate = 'randbee_e_learning_install_update_' . $i;
    if (function_exists($candidate)) {
      $candidate();
    }
  }
}

/**
 * Enable module video_embed_field.
 */
function randbee_e_learning_install_update_7003() {
  module_enable(array('video_embed_field'));
}

/**
 * Enable and revert feature randbee_feature_e_learning_taxonomy.
 */
function randbee_e_learning_install_update_7004() {
  module_enable(array('randbee_feature_e_learning_taxonomy'));
  features_revert_module('randbee_feature_e_learning_taxonomy');
}

/**
 * Enable feature randbee_feature_e_learning_content_type.
 */
function randbee_e_learning_install_update_7005() {
}

/**
 * Revert feature randbee_feature_e_learning_content_type.
 */
function randbee_e_learning_install_update_7006() {
}

/**
 * Enable feature randbee_feature_e_learning_content_type.
 */
function randbee_e_learning_install_update_7007() {
  module_enable(array('randbee_feature_e_learning_content_type'));
}

/**
 * Revert feature randbee_feature_e_learning_content_type.
 */
function randbee_e_learning_install_update_7008() {
  features_revert_module('randbee_feature_e_learning_content_type');
}

/**
 * Enable modules uuid, course.
 */
function randbee_e_learning_install_update_7009() {
  module_enable(array('uuid', 'course'));
}

/**
 * Revert feature randbee_feature_e_learning_content_type.
 */
function randbee_e_learning_install_update_7010() {
  features_revert_module('randbee_feature_e_learning_content_type');
}

/**
 * Revert feature randbee_feature_e_learning_content_type.
 */
function randbee_e_learning_install_update_7011() {
  features_revert_module('randbee_feature_e_learning_content_type');
}

/**
 * Enable modules quiz_question, multichoice, quiz, course_quiz.
 */
function randbee_e_learning_install_update_7012() {
  module_enable(array('quiz_question', 'multichoice', 'quiz', 'course_content', 'course_quiz'));
}

/**
 * Enable module fitvids.
 */
function randbee_e_learning_install_update_7013() {
  module_enable(array('fitvids'));
}

/**
 * Revert feature randbee_feature_e_learning_content_type.
 */
function randbee_e_learning_install_update_7014() {
  features_revert_module('randbee_feature_e_learning_content_type');
}

/**
 * Enable and revert feature randbee_feature_e_learning_views.
 */
function randbee_e_learning_install_update_7015() {
  module_enable(array('randbee_feature_e_learning_views'));
  features_revert_module('randbee_feature_e_learning_views');
}

/**
 * Enable and revert feature main_menu_elearning_waterinneu.
 */
function randbee_e_learning_install_update_7016() {
}

/**
 * Enable module webform.
 */
function randbee_e_learning_install_update_7017() {
  module_enable(array('webform'));
}

/**
 * Revert feature randbee_feature_e_learning_content_type.
 */
function randbee_e_learning_install_update_7018() {
  features_revert_module('randbee_feature_e_learning_content_type');
}

/**
 * Revert features randbee_feature_e_learning_content_type, randbee_feature_e_learning_views.
 */
function randbee_e_learning_install_update_7019() {
  features_revert_module('randbee_feature_e_learning_content_type');
  features_revert_module('randbee_feature_e_learning_views');
}

/**
 * Enable modules short_answer, long_answer, matching, truefalse and quiz_ddlines.
 */
function randbee_e_learning_install_update_7020() {
  module_enable(array('short_answer'));
  module_enable(array('long_answer'));
  module_enable(array('matching'));
  module_enable(array('truefalse'));
  module_enable(array('quiz_ddlines'));
}

/**
 * Enable and revert feature randbee_feature_e_learning_roles.
 */
function randbee_e_learning_install_update_7021() {
  module_enable(array('randbee_feature_e_learning_roles'));
  features_revert_module('randbee_feature_e_learning_roles');
}

/**
 * Revert feature randbee_feature_e_learning_content_type.
 */
function randbee_e_learning_install_update_7022() {
  features_revert_module('randbee_feature_e_learning_content_type');
}

/**
 * Enable module module_missing_message_fixer.
 */
function randbee_e_learning_install_update_7023() {
  module_enable(array('module_missing_message_fixer'));
}

function randbee_e_learning_install_update_7024() {
}

function randbee_e_learning_install_update_7025() {
}

/**
 * Enable module acl.
 */
function randbee_e_learning_install_update_7026() {
  module_enable(array('acl'));
}

/**
 * Enable module content_access.
 */
function randbee_e_learning_install_update_7027() {
  module_enable(array('content_access'));
}

/**
 * Enable modules signup, course_signup, signup_confirm_email, signup_roles.
 */
function randbee_e_learning_install_update_7028() {
  module_enable(array('signup'));
  module_enable(array('course_signup'));
  module_enable(array('signup_confirm_email'));
  module_enable(array('signup_roles'));
}

/**
 * Enable and revert feature randbee_feature_e_learning_permissions.
 */
function randbee_e_learning_install_update_7029() {
  module_enable(array('randbee_feature_e_learning_permissions'));
  features_revert_module('randbee_feature_e_learning_permissions');
}

/**
 * Enable and revert feature main_menu_elearning_waterinneu.
 */
function randbee_e_learning_install_update_7030() {
}

/**
 * Enable and revert feature randbee_feature_e_learning_permissions.
 */
function randbee_e_learning_install_update_7031() {
  module_enable(array('randbee_feature_e_learning_permissions'));
  features_revert_module('randbee_feature_e_learning_permissions');
}

/**
 * Enable and revert feature randbee_feature_e_learning_views.
 */
function randbee_e_learning_install_update_7032() {
  module_enable(array('randbee_feature_e_learning_views'));
  features_revert_module('randbee_feature_e_learning_views');
}

/**
 * Enable and revert feature randbee_feature_e_learning_permissions.
 */
function randbee_e_learning_install_update_7033() {
  module_enable(array('randbee_feature_e_learning_permissions'));
  features_revert_module('randbee_feature_e_learning_permissions');
}

/**
 * Enable and revert feature randbee_feature_e_learning_content_type.
 */
function randbee_e_learning_install_update_7034() {
  module_enable(array('randbee_feature_e_learning_content_type'));
  features_revert_module('randbee_feature_e_learning_content_type');
}

/**
 * Enable and revert feature randbee_feature_course_object.
 */
function randbee_e_learning_install_update_7035() {
  module_enable(array('randbee_feature_course_object'));
  features_revert_module('randbee_feature_course_object');
}

/**
 * Enable module certificate.
 */
function randbee_e_learning_install_update_7036() {
}

/**
 * Enable modules print, print_pdf, certificate.
 */
function randbee_e_learning_install_update_7037() {
	  module_enable(array('print'));
	  module_enable(array('print_pdf'));
	  module_enable(array('certificate'));
}

/**
 * Enable module course_certificate.
 */
function randbee_e_learning_install_update_7038() {
	  module_enable(array('course_certificate'));
}

/**
 * Was: Enable module print_pdf_dompdf.
 */
function randbee_e_learning_install_update_7039() {
//	  module_enable(array('print_pdf_dompdf'));
}

/**
 * Enable modules Votingapi and fivestar.
 */
function randbee_e_learning_install_update_7040() {
	  module_enable(array('fivestar'));
	  module_enable(array('votingapi'));
}

/**
 * Enable and revert feature randbee_feature_e_learning_content_type.
 */
function randbee_e_learning_install_update_7041() {
  module_enable(array('randbee_feature_e_learning_content_type'));
  features_revert_module('randbee_feature_e_learning_content_type');
}

/**
 * Enable and revert feature randbee_feature_course_object.
 */
function randbee_e_learning_install_update_7042() {
  module_enable(array('randbee_feature_course_object'));
  features_revert_module('randbee_feature_course_object');
}

/**
 * Enable and revert feature randbee_feature_e_learning_content_type.
 */
function randbee_e_learning_install_update_7043() {
  module_enable(array('randbee_feature_e_learning_content_type'));
  features_revert_module('randbee_feature_e_learning_content_type');
}

/**
 * Enable and revert feature randbee_feature_e_learning_content_type.
 */
function randbee_e_learning_install_update_7044() {
  module_enable(array('randbee_feature_e_learning_content_type'));
  features_revert_module('randbee_feature_e_learning_content_type');
}

/**
 * Enable and revert feature randbee_feature_e_learning_views.
 */
function randbee_e_learning_install_update_7045() {
  module_enable(array('randbee_feature_e_learning_views'));
  features_revert_module('randbee_feature_e_learning_views');
}

/**
 * Enable and revert feature print_settings_e_learning_waterinneu.
 */
function randbee_e_learning_install_update_7046() {
  module_enable(array('randbee_feature_e_learning_print_settings'));
  features_revert_module('randbee_feature_e_learning_print_settings');
}

/**
 * Revert feature randbee_feature_e_learning_permissions.
 */
function randbee_e_learning_install_update_7047() {
  features_revert_module('randbee_feature_e_learning_permissions');
}
