<?php
/*
 * Copyright (C) 2015
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 as published
 * by the Free Software Foundation.
 *
 * If the program is linked with libraries which are licensed under one of
 * the following licenses, the combination of the program with the linked
 * library is not considered a "derivative work" of the program:
 *
 *     - Apache License, version 2.0
 *     - Apache Software License, version 1.0
 *     - GNU Lesser General Public License, version 3
 *     - Mozilla Public License, versions 1.0, 1.1 and 2.0
 *     - Common Development and Distribution License (CDDL), version 1.0
 *
 * Therefore the distribution of the program linked with libraries licensed
 * under the aforementioned licenses, is permitted by the copyright holders
 * if the distribution is compliant with both the GNU General Public
 * License version 2 and the aforementioned licenses.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
 * Public License for more details.
 */

function n52_waterinneu_menu_form_menu_edit_item_alter(&$form, &$form_state, $form_id) {
	if ($form_state['build_info']['args'][0] == 'edit') {
		$item = $form_state['build_info']['args'][1];

		$form['ignore_access_roles'] = array(
				'#type' => 'checkboxes',
				'#multiple' => TRUE,
				'#title' => t("Ignore access"),
				'#options' => user_roles(),
				'#description' => t("If a user with one of the selected roles has no access to the menu item's path, the menu item is <strong>not</strong> hidden."),
				'#default_value' => empty($item['options']['ignore_access_roles']) ? array() : $item['options']['ignore_access_roles'],
		);

		$form['#validate'][] = 'n52_waterinneu_menu_form_menu_edit_item_validate';
	}
}

function n52_waterinneu_menu_form_menu_edit_item_validate(&$form, &$form_state) {
	if (isset($form_state['values']['ignore_access_roles'])) {
		$form_state['values']['options']['ignore_access_roles'] = $form_state['values']['ignore_access_roles'];

		$form_state['values']['options']['alter'] = TRUE;
	}
}


function n52_waterinneu_menu_translated_menu_link_alter(&$link, $map) {
	if (!empty($link['options']['ignore_access_roles']) && empty($link['access'])) {

		global $user;

		// Get role ids for which the ignore access option applies.
		$rids = array_values($link['options']['ignore_access_roles']);

		$matching_rids = array_intersect(array_keys($user->roles), $rids);

		if (!empty($matching_rids)) {
			// User has one of the specified roles: override menu link access.
			$link['access'] = TRUE;

			// Localize. This must be done because it is only done for links with
			// access TRUE in _menu_link_translate.
			_menu_item_localize($link, $map, TRUE);
		}
	}
}